server:
  port: 8081
http:
    request:
        #从连接池中获取到连接的最长时间
        connectionRequestTimeout: 500
        #数据传输的最长时间
        connectTimeout: 2000
        #提交请求前测试连接是否可用
        socketTimeout: 10000
        #提交请求前测试连接是否可用
        staleConnectionCheckEnabled: true

    pool:
       #设置连接总数
       maxTotal: 200
       #设置每个地址的并发数
       defaultMaxPerRoute: 100

weixin:
    url: https://api.weixin.qq.com/cgi-bin/token
    appid: wx05aaf675c8f7b3ed
    appsecret: 93187bebc44df53e567692d39173f0a3

elasticSearch:
    clusterName: elasticSearch-zheng
    nodeName: node-1
    servers: 192.168.48.129:9300,192.168.48.131:9300,192.168.48.132:9300

kafka:
    servers: 192.168.48.129:9092,192.168.48.131:9092,192.168.48.132:9092
    topic: yrw-log

#    JavaMailSender 邮件发送的配置
spring:
  mail:
    host: smtp.163.com
    username: zhengwc17@163.com
    password: zzz123456789
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true